name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Chạy khi push lên nhánh main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Plan Infrastructure
        run: terraform plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan


  apply:
    runs-on: ubuntu-latest
    needs: plan # Phụ thuộc vào job "plan"
    steps:
      - name: Download Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Apply Infrastructure
        run: terraform apply tfplan

  destroy: # Job phá hủy, cần thận khi sử dụng
    runs-on: ubuntu-latest
    needs: apply # Phụ thuộc vào job "apply"
    steps:
      # ... (các bước tương tự như job "apply", nhưng dùng `terraform destroy -auto-approve`) ...
